---
- name: Configure PHP Dev Workstations
  hosts: workstations
  remote_user: kaskshad

  vars:
    site_ssl: false

  pre_tasks:
    - name: Install Required Packages
      become: true
      ansible.builtin.package:
        name: git
        state: present

  roles:
    - role: code
      tags: code
    - role: nodejs
      tags: [node, nodejs]
    - role: geerlingguy.php-versions
      tags: [php, dev]
      become: true
    - role: geerlingguy.php
      tags: [php, dev]
      become: true
    - role: geerlingguy.composer
      tags: [php, composer]
      become: true
    - role: geerlingguy.mysql
      tags: [dev, mysql]
      become: true
    - role: drivers
      tags: [mssql, ibm]
      become: true
    - role: site-configs
      tags: sites
      become: true

# vim: ft=yaml.ansible
