---
- name: Configure PHP Dev Workstations
  hosts: workstations

  vars:
    site_ssl: false

  pre_tasks:
    - name: Install Required Packages
      become: true
      ansible.builtin.package:
        name: git
        state: present

    - name: Install Php and Composer
      become: true
      tags: php
      block:
        - name: Install PHP Packages
          ansible.builtin.dnf:
            state: present
            name: "{{ item }}"
          loop: "{{ php_packages }}"

        # TODO: Set PHP FPM to run as user

        - name: Install Composer and Sqlite
          ansible.builtin.dnf:
            state: present
            name:
              - composer
              - sqlite3

  roles:
    - role: code
      tags: code
    - role: nodejs
      tags: [node, nodejs]
    - role: drivers
      tags: [mssql, ibm]
      become: true
    - role: site-configs
      tags: sites
      become: true

# vim: ft=yaml.ansible
