---
- name: Configure Workstations
  hosts: workstations
  remote_user: kaskshad

  pre_tasks:
    - name: Update the System
      become: true
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist

    - name: Install Required Packages
      become: true
      ansible.builtin.apt:
        pkg:
          - git
        state: present

  roles:
    - role: code
      tags: code
    - role: geerlingguy.php-versions
      tags: [php, dev]
      become: true
    - role: geerlingguy.php
      tags: [php, dev]
      become: true

# vim: ft=yaml.ansible
