- name: Install User Global Composer Packages
  become: false
  community.general.composer:
    command: require
    global_command: true
    arguments: cpriego/valet-linux
  tags:
    - package

- name: Install Valet PreReqs
  become: true
  ansible.builtin.apt:
    state: present
    package:
      - libnss3-tools
      - jq
      - xsel
      - nginx
      - dnsmasq
      - inotify-tools
  tags: valet

- name: Add composer bin to path
  become: false
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export PATH="$PATH:$HOME/.config/composer/vendor/bin"'
    state: present
  tags: valet

- name: Allow Sudo without Password
  become: true
  ansible.builtin.copy:
    dest: /etc/sudoers.d/valet-install
    content: "{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL"
    owner: root
    group: root
    mode: "0600"

- name: Install Valet Configurations
  become: false
  ansible.builtin.command:
    cmd: "{{ ansible_env.HOME }}/.config/composer/vendor/bin/valet install"
    creates: /opt/valet-linux

- name: Park Sites Path with Valet
  become: false
  ansible.builtin.command:
    cmd: "{{ ansible_env.HOME }}/.config/composer/vendor/bin/valet park"
    chdir: "{{ site_path }}"

- name: Configure SSL for Each Site
  become: false
  with_items: "{{ sites_repositories }}"
  ansible.builtin.command:
    cmd: "{{ ansible_env.HOME }}/.config/composer/vendor/bin/valet secure {{ item.name }}"
    chdir: "{{ site_path }}"
    creates: "{{ ansible_env.HOME }}/.valet/Certificates/{{ item.name }}.test.crt"

- name: Remove Sudo Override
  become: true
  ansible.builtin.file:
    path: /etc/sudoers.d/valet-install
    state: absent

# vim: ft=yaml.ansible:
