---
- name: Install Required Packages
  ansible.builtin.package:
    name:
      - debconf-utils
      - odbcinst1debian2
      - odbcinst
      - libodbc1
    state: present

- name: Copy Ibm Deb Package
  ansible.builtin.copy:
    src: ibm-iaccess-1.1.0.11-1.0.amd64.deb
    dest: /tmp/ibm-iaccess-driver.deb
    remote_src: false
    owner: root
    group: root
    mode: '0664'

- name: Install DB2 Driver deb Package
  ansible.builtin.apt:
    deb: /tmp/ibm-iaccess-driver.deb

# vim: ts=2 tw=2 et ft=yaml.ansible
