---
- name: Add Microsoft Repo
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/config/rhel/9/prod.repo
    dest: /etc/yum.repos.d/mssql-release.repo
    mode: "0644"
    owner: root
    group: root

- name: Remove Possible Conflicting Packages
  ansible.builtin.dnf:
    state: absent
    name:
      - unixODBC-utf16
      - unixODBC-utf16-devel

- name: Install MSSQL Odbc Driver
  ansible.builtin.dnf:
    name: msodbcsql18
    state: present
    update_cache: true
  environment:
    ACCEPT_EULA: "Y"
