---
- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Set Nginx to run as normal user
  ansible.builtin.replace:
    path: /etc/nginx/nginx.conf
    regexp: "www-data"
    replace: "{{ ansible_user }}"

- name: Create Nginx Site Configs
  ansible.builtin.include_tasks: nginx.yml
  with_items: "{{ sites_repositories }}"

- name: Add hosts file entries
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1    {{ item.name }}.test"
    state: present
  with_items: "{{ sites_repositories }}"

- name: Set Nginx to Enabled
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true
# vim: ts=2 tw=2 et ft=yaml.ansible
