---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    install_recommends: false

- name: Set Nginx to run as normal user
  ansible.builtin.replace:
    path: /etc/nginx/nginx.conf
    regexp: "www-data"
    replace: "{{ ansible_user }}"

- name: Create Nginx Site Configs
  ansible.builtin.include_tasks: nginx.yml
  with_items: "{{ sites_repositories }}"

- name: Add hosts file entries
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1    {{ item.name }}.test"
    state: present
  with_items: "{{ sites_repositories }}"

# vim: ts=2 tw=2 et ft=yaml.ansible
