---
- name: Set Variable for Config File
  ansible.builtin.set_fact:
    site_conf: "/etc/nginx/conf.d/{{ item.name }}.conf"

- name: Check if the Available Config Exists
  ansible.builtin.stat:
    path: "{{ site_conf }}"
  register: site_available

- name: Check if the Config is Enabled
  ansible.builtin.stat:
    path: "{{ site_conf }}"
  register: site_enabled

- name: Create Site Config File
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ site_conf }}"
    owner: root
    group: root
    mode: "0644"
  when: ( not site_available.stat.exists )
# vim: ts=2 tw=2 et ft=yaml.ansible
