---
php_packages:
  - php
  - php-apcu
  - php-bcmath
  - php-bz2
  - php-cgi
  - php-cli
  - php-common
  - php-curl
  - php-dba
  - php-devel
  - php-enchant
  - php-fpm
  - php-gd
  - php-gmp
  - php-intl
  - php-ldap
  - php-mbstring
  - php-memcached
  - php-odbc
  - php-opcache
  - php-pspell
  - php-readline
  - php-redis
  - php-snmp
  - php-soap
  - php-sqlite3
  - php-tidy
  - php-xdebug
  - php-xml
  - php-xmlrpc
  - php-xsl
  - php-zip
